version: 2
executorType: docker
containerInfo:
  - image: golang:1.8.3
    cmd: ["/bin/bash"]
stages:
  build:
    parallel: 1
    workDir: /go/src/github.com/palantir/amalgomate
    environment:
      - PROJECT: amalgomate
    steps:
      - type: checkout
      - type: cache-restore
        key: godel-{{ checksum "godelw" }}
      - type: shell
        name: "Verify godel version"
        command: ./godelw version
      - type: cache-save
        key: godel-{{ checksum "godelw" }}
        paths:
          - /root/.godel
      - type: shell
        name: "Verify Go version"
        command: go version
      - type: shell
        name: "Install packages"
        command: go install $(./godelw packages)
      - type: shell
        name: "Create test output directory"
        command: mkdir -p "/tmp/test-results/$PROJECT"
      - type: shell
        name: "Run godel verification"
        command: ./godelw verify --apply=false --junit-output="/tmp/test-results/$PROJECT/$PROJECT-tests.xml"
      - type: test-results-store
        path: /tmp/test-results
      - type: artifacts-store
        path: /tmp/test-results
        destination: test-results
      - type: deploy
        name: "Deploy docs"
        command: |
          set -eu
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            ./godelw github-wiki --docs-dir docs --repository=git@github.com:palantir/amalgomate.wiki.git
          fi
