products:
  amalgomate:
    build:
      main-pkg: .
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
      version-var: github.com/palantir/amalgomate/vendor/github.com/palantir/pkg/cobracli.version
  amalgomate-plugin:
    build:
      main-pkg: ./godelplugin
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
group-id: com.palantir
